apiVersion: es.upv.grycap/v1
kind: KorgiJob
metadata:
  labels:
    app.kubernetes.io/name: korgijob
    app.kubernetes.io/instance: korgijob-sample
    app.kubernetes.io/part-of: korgi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: korgi
  name: korgijob-sample
spec:
  # TODO(user): Add fields here
