# permissions for end users to view ats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: at-viewer-role
rules:
- apiGroups:
  - cnat.esparig.github.io
  resources:
  - ats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cnat.esparig.github.io
  resources:
  - ats/status
  verbs:
  - get
